branches:
  only:
  - gcs

language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_script:
    - composer require codeclimate/php-test-reporter --dev
    - composer selfupdate
    - composer install

script:
    - phpunit -c ./build.xml
    - phpcs --extensions=php -p --standard=PSR2 ./
    - phpunit --bootstrap www/SiGA/autoload.php --debug --coverage-text test
    - phpunit --testsuite=unit --coverage-text --coverage-clover build/logs/clover.xml

