branches:
  only:
  - gcs

language: php

script:
    - phpunit --testsuite=unit --coverage-text --coverage-clover build/logs/clover.xml

php:
    - 5.6

before_script:
    - composer selfupdate
    - composer install
