branches:
  only:
  - gcs

language: php

env:
    - RUN=phpunit
    - RUN=vendor/bin/phpunit

script: RUN

php:
    - 5.6

before_script:
    - composer selfupdate
    - composer --version
    - composer install
